version: "3.8"
services:
  # Mysql database container
  mysql_db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: harmony_db
      MYSQL_USER: harmony
      MYSQL_PASSWORD: harmony
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - harmony_network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql_db
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql_db
    networks:
      - harmony_network

  www:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: harmony_project
    ports:
      - "8080:8000"
    environment:
      DATABASE_URL: "mysql://harmony:harmony@mysql_db:3306/harmony_db"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    depends_on:
      - mysql_db
    networks:
      - harmony_network

networks:
  harmony_network:

volumes:
  db_data: